version: "3.3"
   
services:
  db:
    image: cimg/postgres:14.4
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    image: opus10/circleci-public-django-app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
